In [40]:
import numpy as np
import pandas as pd

In [41]:
df=pd.read_csv("output.csv")

In [42]:
df.head()

,end_year,intensity,sector,topic,insight,url,region,start_year,impact,added,published,country,relevance,pestle,source,title,likelihood
0,NaN,6.0,Energy,gas,Annual Energy Outlook,http://www.eia.gov/outlooks/aeo/pdf/0383(2017)...,Northern America,NaN,NaN,"January, 20 2017 03:51:25","January, 09 2017 00:00:00",United States of America,2.0,Industries,EIA,U.S. natural gas consumption is expected to in...,3.0
1,NaN,6.0,Energy,oil,Annual Energy Outlook,http://www.eia.gov/outlooks/aeo/pdf/0383(2017)...,Northern America,NaN,NaN,"January, 20 2017 03:51:24","January, 09 2017 00:00:00",United States of America,2.0,Industries,EIA,Reference case U.S. crude oil production is pr...,3.0
2,NaN,6.0,Energy,consumption,Annual Energy Outlook,http://www.eia.gov/outlooks/aeo/pdf/0383(2017)...,Northern America,NaN,NaN,"January, 20 2017 03:51:23","January, 09 2017 00:00:00",United States of America,2.0,Industries,EIA,U.S. petroleum consumption is projected to rem...,3.0
3,NaN,6.0,Environment,oil,WRI Partnership Aims to Foster Supply Chain Tr...,http://www.sustainablebrands.com/news_and_view...,Central America,NaN,NaN,"January, 20 2017 03:26:40","January, 18 2017 00:00:00",Mexico,3.0,Environmental,sustainablebrands.com,"Mars, Unilever, Cargill and Mondelēz are alrea...",2.0
4,NaN,6.0,NaN,market,N-Hexane Market Hit at a CAGR of 5% by 2024 - ...,http://www.sbwire.com/press-releases/n-hexane-...,World,NaN,NaN,"January, 19 2017 00:55:54","January, 18 2017 00:00:00",NaN,2.0,Economic,SBWire,Polymerization will remain top 3 end-users in ...,3.0

In [43]:
df.isnull().sum()

end_year      742
intensity      38
sector        229
topic          93
insight         0
url             0
region        453
start_year    690
impact        966
added           0
published      74
country       650
relevance       1
pestle         93
source          1
title           0
likelihood     38
dtype: int64

In [44]:
df.dtypes
df.describe(include="all")

,end_year,intensity,sector,topic,insight,url,region,start_year,impact,added,published,country,relevance,pestle,source,title,likelihood
count,258.000000,962.000000,771,907,1000,1000,547,310.000000,34.000000,1000,926,350,999.000000,907,999,1000,962.000000
unique,NaN,NaN,18,97,660,670,23,NaN,NaN,910,236,56,NaN,9,403,1000,NaN
top,NaN,NaN,Energy,oil,Monthly Oil Market Report,http://www.eia.gov/radio/,Northern America,NaN,NaN,"July, 17 2016 03:21:18","January, 11 2017 00:00:00",United States of America,NaN,Industries,OPEC,U.S. natural gas consumption is expected to in...,NaN
freq,NaN,NaN,525,403,43,27,132,NaN,NaN,4,34,112,NaN,344,43,1,NaN
mean,2024.930233,10.238046,NaN,NaN,NaN,NaN,NaN,2017.509677,3.176471,NaN,NaN,NaN,2.729730,NaN,NaN,NaN,3.165281
std,15.478961,9.588543,NaN,NaN,NaN,NaN,NaN,4.500799,0.458627,NaN,NaN,NaN,1.196616,NaN,NaN,NaN,0.816531
min,2016.000000,1.000000,NaN,NaN,NaN,NaN,NaN,2016.000000,2.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,1.000000
25%,2018.000000,4.000000,NaN,NaN,NaN,NaN,NaN,2016.000000,3.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,2.000000
50%,2020.000000,8.000000,NaN,NaN,NaN,NaN,NaN,2016.000000,3.000000,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,3.000000
75%,2027.000000,12.000000,NaN,NaN,NaN,NaN,NaN,2017.000000,3.000000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,4.000000
max,2200.000000,96.000000,NaN,NaN,NaN,NaN,NaN,2050.000000,4.000000,NaN,NaN,NaN,7.000000,NaN,NaN,NaN,4.000000

In [45]:
end_year_mean=df["end_year"].mean()
int64_number = np.int64(end_year_mean)

intensity_mean=df["intensity"].mean()
int64_number2 = np.int64(intensity_mean)

start_year_mean =df["start_year"].mean()
int64_number3 = np.int64(start_year_mean)

impact_mean=df["impact"].mean()
int64_number4 = np.int64(impact_mean)

relevence_mean=df["relevance"].mean()
int64_number5 = np.int64(relevence_mean)

likelihood_mean=df["likelihood"].mean()
int64_number6 = np.int64(likelihood_mean)

In [46]:
df["intensity"].replace(np.NaN,int64_number2)

0       6.0
1       6.0
2       6.0
3       6.0
4       6.0
       ...
995     2.0
996    10.0
997    16.0
998     3.0
999     2.0
Name: intensity, Length: 1000, dtype: float64

In [49]:
df["end_year"]=df["end_year"].replace(np.NaN,int64_number)

In [55]:
df.shape[0]

1000